/*
 * static_model.h
 *
 * automatically generated from model.icd
 */

#ifndef STATIC_MODEL_H_
#define STATIC_MODEL_H_

#include <stdlib.h>
#include "iec61850_model.h"

extern IedModel iedModel;
extern LogicalDevice iedModel_VaconFreqConverter;
extern LogicalNode   iedModel_VaconFreqConverter_LLN0;
extern DataObject    iedModel_VaconFreqConverter_LLN0_Mod;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_Mod_q;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_Mod_t;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_Mod_ctlModel;
extern DataObject    iedModel_VaconFreqConverter_LLN0_Beh;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_Beh_stVal;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_Beh_q;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_Beh_t;
extern DataObject    iedModel_VaconFreqConverter_LLN0_Health;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_Health_stVal;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_Health_q;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_Health_t;
extern DataObject    iedModel_VaconFreqConverter_LLN0_NamPlt;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_NamPlt_vendor;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_NamPlt_swRev;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_NamPlt_d;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_NamPlt_configRev;
extern DataAttribute iedModel_VaconFreqConverter_LLN0_NamPlt_ldNs;
extern LogicalNode   iedModel_VaconFreqConverter_DSFC1;
extern DataObject    iedModel_VaconFreqConverter_DSFC1_AnIn0;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn0_mag;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn0_mag_f;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn0_q;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn0_t;
extern DataObject    iedModel_VaconFreqConverter_DSFC1_AnIn1;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn1_mag;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn1_mag_f;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn1_q;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn1_t;
extern DataObject    iedModel_VaconFreqConverter_DSFC1_AnIn2;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn2_mag;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn2_mag_f;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn2_q;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn2_t;
extern DataObject    iedModel_VaconFreqConverter_DSFC1_AnIn3;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn3_mag;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn3_mag_f;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn3_q;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn3_t;
extern DataObject    iedModel_VaconFreqConverter_DSFC1_AnIn4;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn4_mag;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn4_mag_f;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn4_q;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn4_t;
extern DataObject    iedModel_VaconFreqConverter_DSFC1_AnIn5;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn5_mag;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn5_mag_f;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn5_q;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn5_t;
extern DataObject    iedModel_VaconFreqConverter_DSFC1_AnIn6;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn6_mag;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn6_mag_f;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn6_q;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn6_t;
extern DataObject    iedModel_VaconFreqConverter_DSFC1_AnIn7;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn7_mag;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn7_mag_f;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn7_q;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn7_t;
extern DataObject    iedModel_VaconFreqConverter_DSFC1_AnIn8;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn8_mag;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn8_mag_f;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn8_q;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn8_t;
extern DataObject    iedModel_VaconFreqConverter_DSFC1_AnIn9;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn9_mag;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn9_mag_f;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn9_q;
extern DataAttribute iedModel_VaconFreqConverter_DSFC1_AnIn9_t;



#define IEDMODEL_VaconFreqConverter (&iedModel_VaconFreqConverter)
#define IEDMODEL_VaconFreqConverter_LLN0 (&iedModel_VaconFreqConverter_LLN0)
#define IEDMODEL_VaconFreqConverter_LLN0_Mod (&iedModel_VaconFreqConverter_LLN0_Mod)
#define IEDMODEL_VaconFreqConverter_LLN0_Mod_q (&iedModel_VaconFreqConverter_LLN0_Mod_q)
#define IEDMODEL_VaconFreqConverter_LLN0_Mod_t (&iedModel_VaconFreqConverter_LLN0_Mod_t)
#define IEDMODEL_VaconFreqConverter_LLN0_Mod_ctlModel (&iedModel_VaconFreqConverter_LLN0_Mod_ctlModel)
#define IEDMODEL_VaconFreqConverter_LLN0_Beh (&iedModel_VaconFreqConverter_LLN0_Beh)
#define IEDMODEL_VaconFreqConverter_LLN0_Beh_stVal (&iedModel_VaconFreqConverter_LLN0_Beh_stVal)
#define IEDMODEL_VaconFreqConverter_LLN0_Beh_q (&iedModel_VaconFreqConverter_LLN0_Beh_q)
#define IEDMODEL_VaconFreqConverter_LLN0_Beh_t (&iedModel_VaconFreqConverter_LLN0_Beh_t)
#define IEDMODEL_VaconFreqConverter_LLN0_Health (&iedModel_VaconFreqConverter_LLN0_Health)
#define IEDMODEL_VaconFreqConverter_LLN0_Health_stVal (&iedModel_VaconFreqConverter_LLN0_Health_stVal)
#define IEDMODEL_VaconFreqConverter_LLN0_Health_q (&iedModel_VaconFreqConverter_LLN0_Health_q)
#define IEDMODEL_VaconFreqConverter_LLN0_Health_t (&iedModel_VaconFreqConverter_LLN0_Health_t)
#define IEDMODEL_VaconFreqConverter_LLN0_NamPlt (&iedModel_VaconFreqConverter_LLN0_NamPlt)
#define IEDMODEL_VaconFreqConverter_LLN0_NamPlt_vendor (&iedModel_VaconFreqConverter_LLN0_NamPlt_vendor)
#define IEDMODEL_VaconFreqConverter_LLN0_NamPlt_swRev (&iedModel_VaconFreqConverter_LLN0_NamPlt_swRev)
#define IEDMODEL_VaconFreqConverter_LLN0_NamPlt_d (&iedModel_VaconFreqConverter_LLN0_NamPlt_d)
#define IEDMODEL_VaconFreqConverter_LLN0_NamPlt_configRev (&iedModel_VaconFreqConverter_LLN0_NamPlt_configRev)
#define IEDMODEL_VaconFreqConverter_LLN0_NamPlt_ldNs (&iedModel_VaconFreqConverter_LLN0_NamPlt_ldNs)
#define IEDMODEL_VaconFreqConverter_DSFC1 (&iedModel_VaconFreqConverter_DSFC1)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn0 (&iedModel_VaconFreqConverter_DSFC1_AnIn0)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn0_mag (&iedModel_VaconFreqConverter_DSFC1_AnIn0_mag)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn0_mag_f (&iedModel_VaconFreqConverter_DSFC1_AnIn0_mag_f)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn0_q (&iedModel_VaconFreqConverter_DSFC1_AnIn0_q)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn0_t (&iedModel_VaconFreqConverter_DSFC1_AnIn0_t)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn1 (&iedModel_VaconFreqConverter_DSFC1_AnIn1)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn1_mag (&iedModel_VaconFreqConverter_DSFC1_AnIn1_mag)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn1_mag_f (&iedModel_VaconFreqConverter_DSFC1_AnIn1_mag_f)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn1_q (&iedModel_VaconFreqConverter_DSFC1_AnIn1_q)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn1_t (&iedModel_VaconFreqConverter_DSFC1_AnIn1_t)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn2 (&iedModel_VaconFreqConverter_DSFC1_AnIn2)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn2_mag (&iedModel_VaconFreqConverter_DSFC1_AnIn2_mag)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn2_mag_f (&iedModel_VaconFreqConverter_DSFC1_AnIn2_mag_f)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn2_q (&iedModel_VaconFreqConverter_DSFC1_AnIn2_q)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn2_t (&iedModel_VaconFreqConverter_DSFC1_AnIn2_t)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn3 (&iedModel_VaconFreqConverter_DSFC1_AnIn3)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn3_mag (&iedModel_VaconFreqConverter_DSFC1_AnIn3_mag)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn3_mag_f (&iedModel_VaconFreqConverter_DSFC1_AnIn3_mag_f)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn3_q (&iedModel_VaconFreqConverter_DSFC1_AnIn3_q)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn3_t (&iedModel_VaconFreqConverter_DSFC1_AnIn3_t)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn4 (&iedModel_VaconFreqConverter_DSFC1_AnIn4)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn4_mag (&iedModel_VaconFreqConverter_DSFC1_AnIn4_mag)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn4_mag_f (&iedModel_VaconFreqConverter_DSFC1_AnIn4_mag_f)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn4_q (&iedModel_VaconFreqConverter_DSFC1_AnIn4_q)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn4_t (&iedModel_VaconFreqConverter_DSFC1_AnIn4_t)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn5 (&iedModel_VaconFreqConverter_DSFC1_AnIn5)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn5_mag (&iedModel_VaconFreqConverter_DSFC1_AnIn5_mag)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn5_mag_f (&iedModel_VaconFreqConverter_DSFC1_AnIn5_mag_f)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn5_q (&iedModel_VaconFreqConverter_DSFC1_AnIn5_q)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn5_t (&iedModel_VaconFreqConverter_DSFC1_AnIn5_t)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn6 (&iedModel_VaconFreqConverter_DSFC1_AnIn6)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn6_mag (&iedModel_VaconFreqConverter_DSFC1_AnIn6_mag)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn6_mag_f (&iedModel_VaconFreqConverter_DSFC1_AnIn6_mag_f)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn6_q (&iedModel_VaconFreqConverter_DSFC1_AnIn6_q)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn6_t (&iedModel_VaconFreqConverter_DSFC1_AnIn6_t)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn7 (&iedModel_VaconFreqConverter_DSFC1_AnIn7)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn7_mag (&iedModel_VaconFreqConverter_DSFC1_AnIn7_mag)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn7_mag_f (&iedModel_VaconFreqConverter_DSFC1_AnIn7_mag_f)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn7_q (&iedModel_VaconFreqConverter_DSFC1_AnIn7_q)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn7_t (&iedModel_VaconFreqConverter_DSFC1_AnIn7_t)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn8 (&iedModel_VaconFreqConverter_DSFC1_AnIn8)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn8_mag (&iedModel_VaconFreqConverter_DSFC1_AnIn8_mag)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn8_mag_f (&iedModel_VaconFreqConverter_DSFC1_AnIn8_mag_f)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn8_q (&iedModel_VaconFreqConverter_DSFC1_AnIn8_q)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn8_t (&iedModel_VaconFreqConverter_DSFC1_AnIn8_t)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn9 (&iedModel_VaconFreqConverter_DSFC1_AnIn9)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn9_mag (&iedModel_VaconFreqConverter_DSFC1_AnIn9_mag)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn9_mag_f (&iedModel_VaconFreqConverter_DSFC1_AnIn9_mag_f)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn9_q (&iedModel_VaconFreqConverter_DSFC1_AnIn9_q)
#define IEDMODEL_VaconFreqConverter_DSFC1_AnIn9_t (&iedModel_VaconFreqConverter_DSFC1_AnIn9_t)

#endif /* STATIC_MODEL_H_ */

